name: BiomeParanoia
main: com.leontg77.biomeparanoia.Main
version: 1.0
author: LeonTG77
description: When players are in a different biome their name will turn a certain color on tab.

commands:
    bparanoia:
        description: Enable or disable the plugin features.
    bl:
        description: Display a list of biomes with its color.
